name: Run Tests and Push if Passed

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
 
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --quiet --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: run_tests
      run: |
        set -e
        for file in tests/*.py; do
          echo "Running test file: $file"
          python "$file"
        done

    - name: Push changes if tests pass
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated commit after successful tests [skip ci]" || echo "No changes to commit"
        git pull --rebase
        git push origin main
